# CSRF / Cookie signing key. Make this something random! See https://flask.palletsprojects.com/en/stable/config/#SECRET_KEY
SECRET_KEY = "5Fh/gM4PA1NuQlWKXCKtlkeb6iDj01TYz1OtlSJ7I5Y="

# Possible output directories. Delimit with OS path separator (: on unix, ; on Windows)
OUTPUTS = "/tmp/slurp"

# Enable the YTDLP fetcher.
FETCHER_YTDLP_ENABLED = true
# Set a JavaScript runtime for YTDLP to use. This is optional, but YTDLP will run degraded if you don't set this.
# This should be set automatically if you're using the Container distribution of Slurp.
# For example:
# FETCHER_YTDLP_JS_RUNTIMES = {"deno": {"path": "/usr/bin/deno"}}

# Enable the get_iplayer fetcher.
# Note: get_iplayer must be installed separately (we just call the binary).
FETCHER_BBC_IPLAYER_ENABLED = true

# Cobalt fetcher settings.
# Note: you must have a valid Cobalt instance to run queries against. See the README for more information.

# Enable the Cobalt fetcher.
FETCHER_COBALT_ENABLED = false
# Cobalt instance URL (with trailing slash).
FETCHER_COBALT_URL = "http://localhost:9000/"
# OPTIONAL: Cobalt API Key. Omit to use unauthenticated connection (make sure your instance is firewalled correctly!)
# FETCHER_COBALT_KEY = "TESTBADKEY"