[project]
name = "slurp"
version = "0.3.0"
description = "Online media ingest utility"
authors = [
    {name = "embr",email = "git@liclac.eu"},
    {name = "duck.",email = "me@duck.moe"}
]
license = {text = "EUPL-1.2"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask (>=3.1.0,<4.0.0)",
    "watchdog (>=6.0.0,<7.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "flask-wtf (>=1.2.2,<2.0.0)",
    "yt-dlp (>=2025.12.8,<2026.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "gunicorn (==23.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
serve = "slurp:serve"
