[project]
name = "ytdlpls"
version = "0.1.0"
description = "Web UI for yt-dlp"
authors = [
    {name = "embr",email = "git@liclac.eu"}
]
license = {text = "EUPL-1.2"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask (>=3.1.0,<4.0.0)",
    "watchdog (>=6.0.0,<7.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "flask-wtf (>=1.2.2,<2.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
serve = "ytdlpls.app:serve"
